# Generated by Django 4.2.7 on 2024-06-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0005_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
