# Generated by Django 4.2.7 on 2024-06-09 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0007_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
