# Generated by Django 4.2.7 on 2024-06-20 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mod', '0009_article_blog_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
